### ISSUE TITLE
[BUG] (Tome 1, Chapter 2) Creative upgrades quests doesn't check NBT

### ISSUE THREAD

**Issue by Preta-Crowz** [Gogo08190/chroma-endless#10]
### Description of the Bug

Three creative upgrades quests (Def Slot, Upgrade, Ability) doesn't check NBT to detect right item.
This causes craft any of them will complete other two. (They uses same item with different NBT)

### Expected Behaviour

They should check NBT.

### Modpack Version

1.0.6

**Comment by koepss** [comment]
It's fix in next update
