### ISSUE TITLE
[BUG] TiC "Creative Upgrade" requires new smith hammer on every iter

### ISSUE THREAD

**Issue by Preta-Crowz** [Gogo08190/chroma-endless#11]
### Description of the Bug

TiC Creative Upgrade requires Iron Smith Hammer on their recipe.
When user try to craft it, it requires new hammer on every iteration. While only 1 durability will used from hammer.

### Expected Behaviour

They should use entire hammer or allow use of damaged one.

### Modpack Version

1.0.6

### Screenshots

![Recipe of Creative Upgrade. Uses Iron Smith Hammer.](https://user-images.githubusercontent.com/16697820/218233180-3165a2a9-0d7e-433e-a43d-80598f56a692.png)

**Comment by koepss** [comment]
It's fix in next update
