### ISSUE TITLE
[BUG] TiC "Creative Defense Slot" can't be crafted

### ISSUE THREAD

**Issue by Preta-Crowz** [Gogo08190/chroma-endless#12]
### Description of the Bug

Recipe of Creative Defense Slot uses Plate Chestplate on base item.
But recipe requires "Uninited" Plate Chestplate instead of inited one by exact NBT check.
This makes user can't craft this item.

### Expected Behaviour

Recipe should not check exact NBT and allow any plate chestplate.

### Modpack Version

1.0.6

### Screenshots

![Recipe of Creative Defense Slot. Requires "Uninited" Plate Chestplate.](https://user-images.githubusercontent.com/16697820/218233214-53385938-44ce-46ff-8f35-2e4c6e0bfbf4.png)

**Comment by Gogo08190** [comment]
Fix in the next update
