### ISSUE TITLE
[BUG] Problematic recipe of breaker module in Modular Router Mod

### ISSUE THREAD

**Issue by FrnkPsycho** [Gogo08190/chroma-endless#13]
### Description of the Bug

The recipe for Breaker Module in Modular Router has been modified using only diamond pickaxe but the mining level of the module stays in iron pickaxe which cannot be changed thus causing problems such as unable to break obsidians. The mining level was meant to be determined by the pickaxe that used to craft this module in original mod.

### Expected Behaviour

the mining level of the module should be determined by the pickaxe in the recipe.

### Modpack Version

1.0.6

**Comment by Gogo08190** [comment]
It will be fixed in the next update! Thanks :)
