### ISSUE TITLE
[BUG] Tardis "Structure Upgrade" doesn't have recipe while required from quest

### ISSUE THREAD

**Issue by Preta-Crowz** [Gogo08190/chroma-endless#15]
### Description of the Bug

"Structure Upgrade" from Tardis doesn't have recipe.
But this item is required from quest.

### Expected Behaviour

item should have recipe or removed from quest

### Modpack Version

1.0.7b

### Screenshots

![its quest](https://user-images.githubusercontent.com/16697820/219869888-11332233-a7df-4d43-bd84-3fd4515d6ecd.png)

![crafting recipes of item, only anvil things are exist](https://user-images.githubusercontent.com/16697820/219869873-2949854d-a1f9-4133-bf7d-7eec22d430c8.png)

**Comment by koepss** [comment]
Hello It's not a bug, you just have to complete a quest in a station and you get it
it's noted in the wiki

**Comment by Preta-Crowz** [comment]
> Hello It's not a bug, you just have to complete a quest in a station and you get it it's noted in the wiki

There's no ingame information, unless it's wrote on "very unreadable manual".
No one will know unless find its wiki.
