### ISSUE TITLE
[BUG] no recipe for fluid storage disks

### ISSUE THREAD

**Issue by antrobot1234** [Gogo08190/chroma-endless#18]
### Description of the Bug

there is no recipe for any of the fluid storage disks, despite the fact that the fluid storage quest asks for them

### Expected Behaviour

1. look up fluid storage
2. press R
3. there's no recipe

### Modpack Version

1.0.7 hotfix

### Screenshots

![image](https://user-images.githubusercontent.com/21179158/221254849-75ee3199-b9da-43d8-a2cc-da9ec775dfe8.png)

**Comment by Gogo08190** [comment]
![image](https://user-images.githubusercontent.com/41335079/221258617-31f71f81-30a2-4b0c-b7f7-0d8d06071e3e.png)

The recipes works perfectly.

**Comment by antrobot1234** [comment]
![image](https://user-images.githubusercontent.com/21179158/221259538-31c3c5f4-b02d-477a-9bc0-5414d984c7ea.png)

**Comment by Gogo08190** [comment]
Try to relauch or reinstall your modpack.

**Comment by antrobot1234** [comment]
this is on a server.

**Comment by Gogo08190** [comment]
Restart or reinstall server

**Comment by antrobot1234** [comment]
they are apparently banned in the server
