### ISSUE TITLE
[SUGGESTION] Maybe leave issues as "open" till the next version comes out

### ISSUE THREAD

**Issue by togreglove** [Gogo08190/chroma-endless#5]
### Description of Suggestion

If you close an issue I have to go looking through closed issues to see if it's been reported already.  If you mark it instead as fixed in development or fixed in next update and leave it open till the next version ships, I immediately know that you know about the issue and it's handled.  I can understand wanting to have a clean issues tracker, but if I weren't the most thorough reporter, I wouldn't check closed issues before reporting a bug.

### How does this improve the experience?

Prevents duplicate reports of same issue.

**Comment by Gogo08190** [comment]
The issues was automatic closed after the pull request.

**Comment by togreglove** [comment]
Ahh
Dunno how github works, just how reporting works :) Sorry if it's automatic and nothing you can do.
