### ISSUE TITLE
[BUG] Bone blocks marked as "Shovel", but shows with red X while holding shovel

### ISSUE THREAD

**Issue by togreglove** [Gogo08190/chroma-endless#6]
### Description of the Bug

If I go to mine a bone block (large skeletons in desert), it says it needs a shovel, yet when I equip a tetra shovel, it shows a red X.  But when I equip my tetra Pickaxe, it still says shovel, but shows the green check mark. Not priority, but confusing.  In a normal pack, I would just go on and leave it as a mystery, but in an expert pack, I have to question if the pack maker intended me to use some other method instead of the obvious one, since recipes and methods you are used to can be changed to up the difficulty.

### Expected Behaviour

If marked as shovel needed, should be minable with shovel.

### Modpack Version

1.0.6

**Comment by togreglove** [comment]
To add to this, I just noticed the tetra workstation also shows as shovel, though it would probably be axe?

**Comment by togreglove** [comment]
Ok, everything is showing as shovel :)

**Comment by togreglove** [comment]
Nope, a dead bush showed as axe. I can't figure it out

**Comment by Gogo08190** [comment]
Report this to the mod author thanks

**Comment by togreglove** [comment]
The mod author of bone blocks?

**Comment by Gogo08190** [comment]
The one probe .. -_-

**Comment by togreglove** [comment]
Like I said, I think most folks will just let it go without too much thought. I'm looking at the pack from the perspective of potentially hosting it on our server cluster, and want to try to work with you to make the experience as un-confusing and enjoyable as possible for our players. I hope you don't mind me reporting strange and oddball things.
