### ISSUE TITLE
Assembly

### ISSUE THREAD

**Issue by HToshirO** [Gogo08190/chroma-endless#7]
### Description of the Bug

le craft du controller de l'assembly machinery ne fonctionne pas et il n'y a aucun endroit ou se place le controller sur le multiblock

### Expected Behaviour

le controller quelque part ?

### Modpack Version

1.0.6

### Screenshots

![1675953158-sans-titre](https://user-images.githubusercontent.com/53542616/217842746-186290b4-8a04-4ddd-adee-b717cf9d96f2.png)

**Comment by Gogo08190** [comment]
Bonjour le craft fonctionne parfaitement je t'invite à utiliser le schematic cannon de create pour le faire.

**Comment by cnordbakk** [comment]
As Gogo says, use the schematic cannon. The controller, which should be placed in the middle of the front first row, and the block placed under the "chimney" on the top back row isn't obvious from the preview.
