### ISSUE TITLE
[BUG] Potion of Spell Damage II recipe produces wrong potion

### ISSUE THREAD

**Issue by Preta-Crowz** [Gogo08190/chroma-endless#8]
### Description of the Bug

When try to brew Spell Damage II by use glowstone with Spell Damage I, it produces Calming Potion instead of right one.

### Expected Behaviour

Should produce Spell Damage II as JEI shows

### Modpack Version

1.0.6

### Screenshots

![Trying to brew Spell Damage II, use glowstone with Spell Damage I](https://user-images.githubusercontent.com/16697820/218232403-68593ae6-6837-4ef2-bb37-ae0e6731b884.png)
![Result is Calming Potion](https://user-images.githubusercontent.com/16697820/218232441-7e3232c4-a716-48a8-964a-2361028e7f3f.png)

**Comment by Preta-Crowz** [comment]
Mana Regeneration II recipe will produce Calming too.

**Comment by Gogo08190** [comment]
Report this to the mod author

**Comment by Gogo08190** [comment]
@Preta-Crowz 
For your information, Going to the Ars Nouveau github I saw that the bug is already reported :
https://github.com/baileyholl/Ars-Nouveau/issues/840
