### ISSUE TITLE
[BUG] (Tome 2, Chapter 3) Infused Hellshelf quest doesn't complete right after craft item

### ISSUE THREAD

**Issue by Preta-Crowz** [Gogo08190/chroma-endless#9]
### Description of the Bug

When item crafted, its NBT doesn't match with required NBT.
So quest will keep pending until player place and break it to obtain right NBT.

### Expected Behaviour

Quest should be complete right after craft item.

### Modpack Version

1.0.6

**Comment by koepss** [comment]
It's fix in next update
